# Generated by Django 4.2.7 on 2025-03-13 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'Общее'), ('love', 'Любовь'), ('career', 'Карьера'), ('health', 'Здоровье')], max_length=50, verbose_name='Категория')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Шаблон предсказания',
                'verbose_name_plural': 'Шаблоны предсказаний',
            },
        ),
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('date_range', models.CharField(max_length=100, verbose_name='Период')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Знак зодиака',
                'verbose_name_plural': 'Знаки зодиака',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HoroscopePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('prediction', models.TextField(verbose_name='Предсказание')),
                ('love', models.TextField(blank=True, verbose_name='Любовь')),
                ('career', models.TextField(blank=True, verbose_name='Карьера')),
                ('health', models.TextField(blank=True, verbose_name='Здоровье')),
                ('lucky_number', models.IntegerField(blank=True, null=True, verbose_name='Счастливое число')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='horoscope.zodiacsign', verbose_name='Знак зодиака')),
            ],
            options={
                'verbose_name': 'Предсказание',
                'verbose_name_plural': 'Предсказания',
                'ordering': ['-date'],
                'unique_together': {('sign', 'date')},
            },
        ),
    ]
